# Generated by Django 3.1 on 2020-09-03 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0002_auto_20200901_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fav_book_genre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fav_movie_genre',
        ),
        migrations.AddField(
            model_name='user',
            name='fav_book_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_users', to='categories.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='fav_movie_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_users', to='categories.category'),
        ),
    ]
